version: "3.9"

services:
  app:
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  pubsub:
    image: messagebird/gcloud-pubsub-emulator
    ports:
      - "8681:8681"
    environment:
      - "PUBSUB_PROJECT1=local,\
        TEST.TOPIC:TEST.TOPIC.SUB"
